### PR TITLE
Re-overwrite `as_json` to avoid to too much loop

### LINKED ISSUE #91: Unexpected behaviour when calling the to_json method on an UploadingSession object
# This is a Bug Report.

## Description

* What went wrong?
Calling the to_json method on an UploadingSession object is endless

* What did you expect should have happened?
I was expecting the to_json function to return a serialised version of the object

* What was the config you used?
I replicated the issue in IRB with the following:
```
require "active_record"
require "brick_ftp"

session = BrickFTP::API::FileOperation::UploadingSession.create(path: '/test-koshigoe/multi-part-uploaded.txt')
session.to_json

```
* What stacktrace or error message from your provider did you see?
No stacktrace or error message is displayed, the to_json method call just never ends.

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
Centos 7
* ***Stack Trace***:
* ***Provider Error messages***:

Please note that the problem doesn't happen when not requiring active_record.
Only when requiring active_record (version 5.4.1), to_json method calls become endless.

### PR DESCRIPTION
**Pull request by koshigoe**
## What did you implement:

Fixes #91

If `active_support/core_ext/object/json.rb` loaded, it overwrite `Enumerable#as_json`.

https://github.com/rails/rails/blob/1c383df324fdf0b68b3f54a649eb7d2a4f55bcb7/activesupport/lib/active_support/core_ext/object/json.rb#L132-L136

The `BrickFTP::API::FileOperation::UploadingSession` includes `Enumerable`.
When `BrickFTP::API::FileOperation::UploadingSession#as_json` is called, it call `BrickFTP::API::FileOperation::UploadingSession#to_a`.
The `BrickFTP::API::FileOperation::UploadingSession#each` will iterate `available_parts` times.

## How did you implement it:

- overwrite `BrickFTP::API::FileOperation::UploadingSession#as_json`
    - NOTE: return only single part

## How can we verify it:

Add activesupport gem to reproduce problem.

```
$ git diff brick_ftp.gemspec
diff --git a/brick_ftp.gemspec b/brick_ftp.gemspec
index 7d1d5ea..d45c890 100644
--- a/brick_ftp.gemspec
+++ b/brick_ftp.gemspec
@@ -28,6 +28,7 @@ Gem::Specification.new do |spec|
   spec.add_development_dependency 'simplecov', '~> 0.15'
   spec.add_development_dependency 'webmock', '~> 2.1'
   spec.add_development_dependency 'yard', '~> 0.9'
+  spec.add_development_dependency 'activesupport'
 
   spec.add_dependency 'deep_hash_transform', '~> 1.0'
   spec.add_dependency 'inifile', '~> 3.0.0'

$ bundle install
```

Call `#as_json` after `require 'active_support/json'`.

```
$ bin/console
> require 'active_support/json'
> BrickFTP::API::FileOperation::UploadingSession.create(path: '/test-koshigoe/multi-part-uploaded.txt').as_json
=> "...."
```

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** YES

### CODE REVIEW

File: lib/brick_ftp/api/base.rb [hunk 1]
```diff
@@ -73,7 +73,7 @@ def destroy(recursive: false)
       end
 
       def as_json
-        self.class.attributes.each_with_object({}) { |name, res| res[name] = read_property(name) }
+        properties.dup
```
Comment (koshigoe) [inline lib/brick_ftp/api/base.rb]: Breaking change: Change type of Hash key to String.

File: lib/brick_ftp/api/base.rb [hunk 2]
```diff
@@ -94,6 +94,11 @@ def delete_property(key)
 
       private
 
+      def initialize_properties
+        @properties = {}
+        self.class.attributes.each { |key| write_property(key, nil) }
```
Comment (koshigoe) [inline lib/brick_ftp/api/base.rb]: include all attributes.

**Comment by koshigoe** [comment]
shipped: https://rubygems.org/gems/brick_ftp/versions/0.8.0

**Comment by pierreyves-lebrun** [comment]
Thank you very much for this, I confirmed the JSON serialisation itself now happens correctly.
Would it be possible to make sure the to_json function accepts the "options" argument as per the following?

```
def to_json(options = {})
    as_json.to_json
end
```

This is to prevent that some other gems throw the following error when attempting to pass options:
wrong number of arguments (given 1, expected 0)

I appreciate your work as always!

**Comment by koshigoe** [comment]
I fixed it.
https://github.com/koshigoe/brick_ftp/pull/94

**Comment by pierreyves-lebrun** [comment]
Fantastic!
I confirmed the serialisation now happens without warning.

Many thanks
